export const DATA_API_LOAD = 'DATA_API_LOAD';
export const DATA_API_LOAD_RESPONSE = 'DATA_API_LOAD_RESPONSE';
export const DATA_API_ADD = 'DATA_API_ADD';
export const DATA_API_DELETE = 'DATA_API_DELETE';
export const DATA_API_EDIT = 'DATA_API_EDIT';
export const DATA_API_EDIT_CHECK = 'DATA_API_EDIT_CHECK';
